/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as NossoTrabalhoRouteImport } from './routes/nosso-trabalho'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const NossoTrabalhoRoute = NossoTrabalhoRouteImport.update({
  id: '/nosso-trabalho',
  path: '/nosso-trabalho',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/nosso-trabalho': typeof NossoTrabalhoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/nosso-trabalho': typeof NossoTrabalhoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/nosso-trabalho': typeof NossoTrabalhoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/contato' | '/nosso-trabalho' | '/sitemap.xml' | '/trabalhe-conosco'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/contato' | '/nosso-trabalho' | '/sitemap.xml' | '/trabalhe-conosco'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/nosso-trabalho'
    | '/sitemap.xml'
    | '/trabalhe-conosco'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  NossoTrabalhoRoute: typeof NossoTrabalhoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nosso-trabalho': {
      id: '/nosso-trabalho'
      path: '/nosso-trabalho'
      fullPath: '/nosso-trabalho'
      preLoaderRoute: typeof NossoTrabalhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  NossoTrabalhoRoute: NossoTrabalhoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
